# Generated by Django 3.0 on 2020-03-08 17:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('userpage', '0004_auto_20200307_2331'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='post',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='userpage.Post'),
            preserve_default=False,
        ),
    ]
