# Generated by Django 3.0 on 2020-03-23 14:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('userpage', '0010_auto_20200322_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='user_image/Post'),
            preserve_default=False,
        ),
    ]
