# Generated by Django 3.0 on 2020-04-05 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userpage', '0014_auto_20200405_1858'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
