# Generated by Django 3.0 on 2020-04-20 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userpage', '0016_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='likes',
        ),
    ]
