# Generated by Django 3.0 on 2020-04-29 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userpage', '0018_post_reshare'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='reshare',
        ),
    ]
