# Generated by Django 3.0 on 2020-05-04 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpage', '0019_remove_post_reshare'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to='Post'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='userImage',
            field=models.ImageField(upload_to='Profiles'),
        ),
    ]
