# Generated by Django 3.0 on 2020-05-04 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpage', '0020_auto_20200504_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='userImage',
            field=models.ImageField(default='default/default.png', upload_to='Profiles'),
        ),
    ]
