# Generated by Django 3.0 on 2020-05-30 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userpage', '0024_following_follower'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='following',
            name='follower',
        ),
    ]
