# Generated by Django 3.0 on 2020-06-02 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userpage', '0027_profile_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='date',
        ),
    ]
